### PR TITLE
Null checks and version change

### PR DESCRIPTION
**Pull request by Csmith246**

### CODE REVIEW

**Review by kellyhutchins — APPROVED** [review]

**Comment by Csmith246** [comment]
@kellyhutchins Could you also do a publish for this?

**Comment by kellyhutchins** [comment]
@Csmith246  sure let me know when its merged.

**Comment by Csmith246** [comment]
@kellyhutchins Oops, ha, forgot about that. All set, whenever you're ready

**Comment by kellyhutchins** [comment]
@Csmith246  ok its published.

**Pull request merged**
