### PR TITLE
Allow configurable apps to support webmap=default, webscene=default o…

### PR DESCRIPTION
**Pull request by alaframboise**
…r no webmap or scene

Some future 4.x templates will need to be able to support a default 2D and 3D webmap/scene or none at all.

### CODE REVIEW

**Review by driskull — CHANGES_REQUESTED** [review]
@alaframboise can you update the typescript file with these changes?

**Comment by kellyhutchins** [comment]
@alaframboise  @driskull  I made the TypeScript changes - if one of you has time can you review?

**Comment by driskull** [comment]
@alaframboise @kellyhutchins isnt this already supported? I see the code in `_getDefaultId()` already.

**Comment by kellyhutchins** [comment]
@driskull I didn't even check :( I just 'translated' Al's code to TS. I'll look at the getDefaultId tomorrow and see how it works/doesn't with Al's scenario.

**Review by driskull — CHANGES_REQUESTED** [review]
This should already be working, no?

**Comment by alaframboise** [comment]
No what I submitted is different. It allow 3 scenarios:

1. http://www.arcgis.com/apps/Styler/index.html (2D default)
2. http://www.arcgis.com/apps/Styler/index.html?webmap=default (2D default)
3. http://www.arcgis.com/apps/Styler/index.html?webscene=default (3D default)

**Comment by driskull** [comment]
@alaframboise can you verify this is already working? If so, there may just need to be documentation updated.

**Comment by driskull** [comment]
@alaframboise can you provide more info on what you're expecting exactly.

**Comment by alaframboise** [comment]
It's working if you implement the code I submitted. ;) I had to change your new appbase to get this behavior/backwards compatibility for my template.

**Comment by alaframboise** [comment]
1, 2 and 3 above. See the logic here:

https://github.com/Esri/application-base-js/pull/18/files#diff-c8638f92493e03da6d4683836fd50e08R310

**Comment by alaframboise** [comment]
The bottom line is that people should be able to hit the endpoint of a 2D/3D config app and not have to specify a default map or scene.

**Comment by driskull** [comment]
I need a little more. This is changing the boolean properties for enabling fetching webmaps/webscenes to a string. This would be a breaking change.

Need to know what the purpose and use case is so we can implement it in the best way possible.

this also doesn't consider any changes for groups.

**Comment by driskull** [comment]
> The bottom line is that people should be able to hit the endpoint of a 2D/3D config app and not have to specify a default map or scene.

But you can set those defaults in the config so they wont' have to. I'm not sure I follow.

**Pull request closed without merging**
